### ISSUE TITLE
Write a Private transaction tutorial

### ISSUE THREAD

**Issue by Tbaut** [paritytech/wiki#175]
Based on the SS tutorial
- Deploy a sample private contract
- Change a private contract state (variable?)

**Comment by CPerezz** [comment]
If it can help, after doing the config on the SS1 node the ss1.toml file is like this:
`
[parity]
chain = "dev"
base_path = "db.ss1"

[ui]
disable = true

[rpc]
disable = true

[ipc]
disable = true

[dapps]
disable = true

[websockets]
disable = true

[network]
port = 30301
bootnodes = [
"enode://40eea035ebdcdf526510833aa2022629026aa08ba2b7a5910be5e34f0d3b8eb726446fca9a09e927734d2377cf60038133694756b03672ef44cd2a4da3a6a374@192.168.1.33:30302",
"enode://702dcf53f3e6055b16601aaffedac81f7c62ab78619c940add8722caf12e42515663631c12264955625ad444dee8ed900d84ca680c899e7a00b116475774633a@192.168.1.33:30303"
]

[ipfs]
enable = false

[snapshots]
disable_periodic = true

[secretstore]
self_secret = "09af7a3791642577e7a0cb0c34acb182cae41ecc"
disable = false
disable_http = false
http_interface = "local"
http_port = 8010
acl_contract = "ae64822c23a00639a80a23a97427aa8f7bde9048"
server_set_contract = "none"
nodes = [
"76bdce5b5b309b3ae9b82f2208967e1cfec28d89778acf9069765686564fcbdc28f7ce4f09f3219ffc892da35d6dd0113a9d3a541a34e6e590e71026db4cef8c@127.0.0.1:8011",
"fa31995131779da327a52572f25643d69366754bc498d1ee5b35d47f6131cc03ba46261077378971f95b55c380516db9f83d88f1a00f1036a85f5a264d9177d2@127.0.0.1:8012",
"4635bc8ee53d07db03a459766bb03f75e1b94f09b48831af51f73dcbee2d13c09bdf2b029c2df0a9fbc593834b5d3bd19e8ad383324d7302bff896a868e45387@127.0.0.1:8013"
]
interface = "local"
port = 8011
path = "db.ss1/secretstore"

[account]
unlock = ["0x09af7a3791642577e7a0cb0c34acb182cae41ecc"]
password = ["ss1.pwd"]

[private_tx]
enabled = true
signer = "0x09af7a3791642577e7a0cb0c34acb182cae41ecc"
validators = ["0x09af7a3791642577e7a0cb0c34acb182cae41ecc"]
passwords = "ss1.pwd"
account = "0x09af7a3791642577e7a0cb0c34acb182cae41ecc"
sstore_url = "http://localhost:8082"
sstore_threshold = 0
`
I've deployed the private smartcontract and put it's bytecode on the first suggested curl of: [https://github.com/paritytech/wiki/blob/master/Private-Transactions.md]

Which will be something like: 
`curl --data '{"method":"parity_composeTransaction","params":[{"from":"0x5cb3fbb516ad63186d1b440a684201685b810be5","data":"0x608060....754600029"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`

I get a Tx object on a json.

Now it's time to Sign it as the documentation says. Should now call the parity_postTransaction method? If it's true, I've to hash the full JSON?
I'm stuck here. because I don't know if this step is missing on the docs.

Apart from that, It will be nice to have on the tutorial the Pre-requisites section where is explained ->
> Contracts registry must be deployed on the chain

Thanks in advice!!
