### ISSUE TITLE
Layout is broken on small screens

### ISSUE THREAD

**Issue by kirushik** [paritytech/wiki#27]

**Comment by 5chdn** [comment]
Yeah noticed that too. I'm not sure if we have broken that or whether the theme was never mobile friendly.

**Comment by amaurymartiny** [comment]
The theme (http://hyde.getpoole.com) is responsive, but not the way we want. If you try this demo website, the black sidebar goes on top of the content on small screens, which becomes unreadable since we have a long sidebar. I would rather imagine a menu button to show/hide the sidebar.

I think it's too much effort to tweak this theme. I found this similar one http://lanyon.getpoole.com, will make a PR asap.
